version: "3"
services:
  app:
    ports:
      - "8000:80"
    build: ./docker/php
    container_name: pokemon
    volumes:
      - .:/var/www/html
    depends_on:
      - mysql

  mysql:
    image: mysql:8.0
    platform: linux/x86_64
    container_name: pokemon_db
    env_file: ./docker/mysql/mysql.env
    environment:
      - TZ=Asia/Tokyo
    ports:
      - "3306:3306"
    volumes:
      - ./docker/mysql/conf:/etc/mysql/conf.d/:ro
      - mysqldata:/var/lib/mysql
    networks:
      - default

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOSTS=mysql
      - PMA_USER=root
      - PMA_PASSWORD=root
    ports:
      - 8081:80
    restart: always
    links:
      - mysql:mysql

      # コンテナが削除されてもデータが消えずに保持される
volumes:
  mysqldata: